[project]
name = "torneos-modena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"streamlit>=1.42.0",
	"requests>=2.32.0",
]
